---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644

- name: Ensure that epel-release installed.
  yum:
    name: epel-release
    state: present

- name: Ensure nginx is installed.
  yum:
    name: "{{ nginx_package_name }}"
    state: present

- name: Just force systemd to reread config
  systemd:
    daemon_reload: yes
