---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: jrei/systemd-ubuntu
    privileged: true
    pre_build_image: true
  - name: centos
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
