---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: jrei/systemd-ubuntu
    privileged: true
    pre_build_image: true
  - name: centos
    image: centos/systemd
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
