---
- name: Inclue OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specic tasks.
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Add users to docker group.
  user:
    name: "{{ docker_user }}"
    group: docker
